"""empty message

Revision ID: 601ed1eaa7d0
Revises: ae22160333ba
Create Date: 2018-10-30 19:56:09.528767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601ed1eaa7d0'
down_revision = 'ae22160333ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_requests', sa.Column('optin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration_requests', 'optin')
    # ### end Alembic commands ###
